name: Node.js CI

on:
  push:
    branches:
      - main  # Run the CI on `main` branch pushes
  pull_request:
    branches:
      - main  # Run the CI on PRs targeting `main`

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Specify the Node.js version you want to use

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run tests (optional, modify if you have a test script)
      - name: Run tests
        run: npm test

      # Build the project (for Express app, you might not need a build step)
      - name: Build app
        run: echo "No build step required for Express."

      # Add any additional steps as required (linting, type-checking, etc.)
